<html>
<!程序名称：12-17.php>
<!程序功能：添加学生信息处理程序。>

<head>
<title>添加学生信息处理程序</title>
</head>
<body>
<?php
$formdata=array();
if(count($http_post_vars))
{
while(list($key,$value)=each($http_post_vars))
{
$formdata[strtolower($key)]=$value;
}
}
$mysqluser="root";
$mysqlpass="123456";
$dbname="mydb";
$tablename="user";
$limit="5";
?>
<table>
<tr><td>
<?php
$name=$formdata['name'];
$age=$formdata['age'];
$phone=$formdata['phone'];
$address=$formdata['address'];
$eduction=$formdata['education'];
echo"连接数据库";
$db_connect=mysql_connect('localhost',$mysqluser,$mysqlpass);
mysql_select_db($dbname);
mysql_query("set names 'gb2312'");
if(!$db_connect)
{
echo"数据库连接不成功!";
?>
</td></tr>
</table>
<?php
exit;
}
?>
<?php

$seldb=mysql_select_db($dbname,$db_connect);
if($action=="add")
{
$insertquery="INSERT INTO `user` ( `id` , `name` , `age` , `phone` , `address` , `education` )
value(NULL,'$name','$age','$phone','$address','$education')";
echo"用户添加成功!";
}
else
{echo"学生添中不成功.";}
?>
<?php
$db_close=mysql_close($db_connect);
?>
<p>关闭数据库!</p>
</body>
</html>